services:
  rails_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: rails_app
    container_name: rails_app
    ports:
      - "3000:3000"
    networks:
      - app_network
    env_file: rails_app.env
    depends_on:
      - postgres

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: webserver
    container_name: webserver
    ports:
      - "8080:80"  # Fix this: map host 8080 to container 80
    networks:
      - app_network
    depends_on:
      - rails_app

  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: rails
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
