name: CI/CD

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: v1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Rails app and NGINX Docker images to ECR
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com

          IMAGE_URI_APP=$ECR_REGISTRY/ror-app-repo-app:${IMAGE_TAG}
          IMAGE_URI_NGINX=$ECR_REGISTRY/ror-app-repo-nginx:${IMAGE_TAG}

          echo "Building Rails app image: $IMAGE_URI_APP"
          docker build -t $IMAGE_URI_APP -f docker/app/Dockerfile .
          docker push $IMAGE_URI_APP

          echo "Building NGINX image: $IMAGE_URI_NGINX"
          docker build -t $IMAGE_URI_NGINX -f docker/nginx/Dockerfile .
          docker push $IMAGE_URI_NGINX

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init and Apply
        working-directory: infrastructure
        run: |
          terraform init
          terraform apply -auto-approve
